# Generated by Django 5.0.6 on 2025-05-07 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('full_journal', models.TextField()),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('field', models.CharField(max_length=25)),
                ('post_status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='Published', max_length=15)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('link_to_profile', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor_id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('special_note', models.CharField(blank=True, max_length=255, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_published',),
            },
        ),
    ]
