# Generated by Django 6.0.3 on 2026-04-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
