# Generated by Django 5.0.6 on 2024-08-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_code',
            field=models.CharField(max_length=10),
        ),
    ]
