# Generated by Django 5.0.6 on 2025-04-17 06:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_code',
            field=models.CharField(default=uuid.uuid4, max_length=10),
        ),
    ]
