# Generated by Django 6.0.3 on 2026-04-03 04:55

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='post_code',
            field=models.CharField(default=article.models.generate_post_code, max_length=10, unique=True),
        ),
    ]
